<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>protocol</artifactId>
	<name>protocol</name>
	<url>http://maven.apache.org</url>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<parent>
		<groupId>cn.game</groupId>
		<artifactId>server</artifactId>
		<version>1.0</version>
	</parent>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>2.5</version>
			</plugin>
	<!-- 添加 os-maven-plugin 以识别操作系统 -->
<!--        <plugin>-->
<!--            <groupId>kr.motd.maven</groupId>-->
<!--            <artifactId>os-maven-plugin</artifactId>-->
<!--            <version>1.7.1</version>-->
<!--            <executions>-->
<!--                <execution>-->
<!--                    <phase>initialize</phase>-->
<!--                    <goals>-->
<!--                        <goal>detect</goal>-->
<!--                    </goals>-->
<!--                </execution>-->
<!--            </executions>-->
<!--        </plugin>-->
<!--		<plugin>-->
<!--            <groupId>org.xolstice.maven.plugins</groupId>-->
<!--            <artifactId>protobuf-maven-plugin</artifactId>-->
<!--            <version>0.6.1</version> -->
<!--            <configuration>-->
<!--                <protoSourceRoot>src/main/java/cn/game/protocol/protos</protoSourceRoot>-->
<!--                <outputDirectory>${project.build.directory}/generated-sources</outputDirectory>-->
<!--                <attachProtoSources>true</attachProtoSources>-->
<!--                <protocArtifact>com.google.protobuf:protoc:3.12.2:exe:${os.detected.classifier}</protocArtifact>-->
<!--            </configuration>-->
<!--            <executions>-->
<!--                <execution>-->
<!--                    <goals>-->
<!--                        <goal>compile</goal>-->
<!--                    </goals>-->
<!--                </execution>-->
<!--            </executions>-->
<!--        </plugin>-->
        
        
        
        
		</plugins>

	</build>

	<dependencies>

		<dependency>
			<groupId>cn.game</groupId>
			<artifactId>util</artifactId>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.velocity/velocity -->
		<dependency>
			<groupId>org.apache.velocity</groupId>
			<artifactId>velocity</artifactId>
			<version>1.7</version>
		</dependency>

		<!--
		https://mvnrepository.com/artifact/commons-collections/commons-collections -->
		<dependency>
			<groupId>commons-collections</groupId>
			<artifactId>commons-collections</artifactId>
			<version>3.1</version>
		</dependency>

		<!--
		https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java -->
		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>3.12.2</version>
		</dependency>

<!-- https://mvnrepository.com/artifact/com.github.javaparser/javaparser-core -->
<dependency>
    <groupId>com.github.javaparser</groupId>
    <artifactId>javaparser-core</artifactId>
    <version>3.25.10</version>
</dependency>


	</dependencies>


</project>
