syntax = "proto3";
package cn.game.protocol.protobuf;
//option optimize_for = LITE_RUNTIME;

import "RewardMsg.proto" ;
import "BaseMsg.proto" ;

//@HandlerPackage cn.game.games.net.game.module.guild
//@ClientHandlerPackage cn.game.simulation.client.handler
//@Function Guild
//@MessageModule 40

//公会的最基础信息,成员和非成员都可以看到的数据，一般在排行榜中使用
message GuildSimpleInfo{
  uint32 id = 1; //公会id
  string name = 2; //公会名称
  int32 level = 3; //公会等级
  int32 icon = 4; //公会ICON
  int32 memberNum = 5; //成员数量
  int32 totalPower = 6; //总战力
  int32 isAutoJoin = 7; //1 快速加入、2 需要验证加入、3 不可加入；
  string masterName= 8; //会长名字
  string declaration = 10;//宣言，工会内外都可见
  string creatorName = 12;//创始人名字
}

//公会的展示数据,成员和非成员都可以看到的数据，查看某个公会时使用。
message GuildShowInfo{
  // 一般需要显示GuildShowInfo这个数据的时候，之前应该都能获取到GuildSimpleInfo
  // 这个数据，所以这里就不单独下发 GuildSimpleInfo
  GuildSimpleInfo simpleInfo = 1;
  repeated GuildMemberInfo members = 9;//成员列表
}

//公会成员信息
message GuildMemberInfo{
  SimplePlayerInfo simplePlayer = 1;//玩家基本信息
  int32 todayContribute = 3;//今日贡献
  int32 weekContribute = 4;//本周贡献
  int32 totalContribute = 5;//累计历史贡献
  int32 totalDonateCount = 7;//累计捐献次数
  int32 joinTime = 10;//加入时间
  int32 position = 11;//职位

}

//公会的完整数据，一般用在查看自己的公会时使用
message GuildAllInfo{
  GuildShowInfo showInfo = 2; //  公共的展示数据
  GuildSharedInfo sharedInfo = 3; // 全体工会成员看到的数据
  GuildPersonalInfo personalInfo = 4; // 自己在工会里的个人数据
}

//所有的工会成员都可以查看到的数据,所有成员看到的应该是一样的数据
//可能根据成员的职位和权限，有些数据客户端不能看到，可以先简单屏蔽一下。
message GuildSharedInfo{
  int32 exp = 1; //公会经验
  int32 liveness = 2;//活跃度
  repeated SimplePlayerInfo applyPlayerList = 10;//申请入会的玩家
  GuildSettingProto setting = 20; //设置信息
  GuildBargainSharedInfo bargain = 21;//砍价相关
}

//自己在公会里的个人数据，一般是和具体的玩法相关的，职位等数据暂时在GuildMemberInfo 里面
// 这些数据只有自己才能看到
message GuildPersonalInfo{
  // 砍价相关
  int32 bargainCount = 1;//当日砍过的次数
  bool isBargainBuy = 2;//是否购买了砍价的物品
   // 当日捐献记录
  map<int32,int32> donate = 5;//key: GuildDonate 表id  value: 对应id的已经捐献次数

}
// 跨服进程返回的公会数据----这个只有服务器用到，客户端可以忽略。
message GuildServiceInfo {
    GuildShowInfo showInfo = 1;
    GuildSharedInfo sharedInfo = 2;
}

//公会设置相关
message GuildSettingProto{
  string wx = 1;//宗主的微信号，已废弃，暂时保留
  int32 wxChangeNum = 2;//微信号修改次数，已废弃，暂时保留
  int32 lastChangeWxTimer = 7;//最后修改微信号时间，已废弃，暂时保留
  string notice = 4;//公告,或者说通知，工会内可见
  map<int32,int32> iconList = 5;//解锁的ICON列表 key ICON id, value 剩余时间戳 秒， -1 表示永久
  int32 lastChangeNameTimer = 6;//最后修改名称时间
}
//公会砍价相关
message GuildBargainSharedInfo{
  int32 bargainItemId = 1;//刷新出来的砍价物品id ： GuildBargain 表id
  int32 totalMemberCount = 2;//累计砍价的人数
  int32 totalBargainCount = 3;//累计砍掉的价格
  //公会砍价记录 key: 砍价人的名字 value: 当日累计砍掉的数量
  map<string,int32> bargainLogMap = 7;
}

//公会操作日志
message GuildLogProto{
  int32  createTimer = 1;//创建时间
  int32  type = 3;//操作类型
  repeated string params = 4;//参数 更具操作类型不同
}

//公会列表
message  GuildListRequest_40000001{
  int32 page = 1;//页码 从1开始 默认1页20条数据
}
message  GuildListResponse_40000002{
  repeated GuildSimpleInfo guildList = 1;
  int32 total = 2;//总条数
  int32 page = 3;//当前页码
}

//查找公会
message  GuildFindRequest_40000003{
  uint32 id = 1;//公会id
}
message  GuildFindResponse_40000004{
  GuildShowInfo guild = 1;
}

//创建公会
message  GuildCreateRequest_40000005{
  string name = 1;//公会名称
  string notice = 2;//公告,或者说通知，工会内可见
  string declaration = 3;//宣言，工会内外都可见
  int32 icon = 4;//ICON
  int32 autoJoin = 5;//1 快速加入、2 需要验证加入、3 不可加入；
}
message  GuildCreateResponse_40000006{
  GuildAllInfo guild = 1;
}

//申请加入公会
message  GuildApplyJoinRequest_40000007{
  uint32 id = 1;//公会id
}
message  GuildApplyJoinResponse_40000008{
  // 只有在公会设置自动加入时，则申请后会返回完整的公会数据，否则没有数据。
  GuildAllInfo guild = 1;
}

//解散公会
message  GuildDissolveRequest_40000011{
}
message  GuildDissolveResponse_40000012{
  bool result = 1;//是否成功
}

//公会设置相关 有值 则替换，没有值 则不修改
message  GuildSettingRequest_40000013{
  string wx = 1;//微信号
  string notice = 2;//公告,或者说通知，工会内可见
  string declaration = 3;//宣言，工会内外都可见
  int32 icon = 4;//ICON
  int32 autoJoin = 5;//1 快速加入、2 需要验证加入、3 不可加入；
  string name = 7;//公会名称
}
message  GuildSettingResponse_40000014{
  bool result = 1;//是否成功
}

//公会职位更改
message  GuildMemberPositionSetRequest_40000015{
  uint32 targetPid = 1;//目标玩家id
  int32 position = 2;//新的职位
}
message  GuildMemberPositionSetResponse_40000016{
  bool result = 1;//是否成功
  int32 position = 2;//新的职位
  uint32 targetPid = 3;//目标玩家id
  uint32 oldPosition = 4;//老的职位
}
//退出公会
message  GuildQuitRequest_40000017{
}
message  GuildQuitResponse_40000018{
  bool result = 1;//是否成功
}

//获取公会信息
message  GuildInfoRequest_40000021{
}
message GuildInfoResponse_40000022{
  GuildAllInfo info = 1;
}

//解散公会 通知玩家退出公会
message GuildQuitPush_40000024
{
  int32 quitType = 1; // 0 自己退出 1 会长踢出 2 会长主动解散 3 公会活跃度低强制解散
}

//处理玩家申请通知，不管是同意还是拒绝
message GuildApplyProcessedPush_40100001
{
    int64 guildId = 1;//
    int64 playerId = 2;//
}


//公会日志请求
message GuildLogRequest_40000025{

}
message GuildLogResponse_40000026{
    repeated GuildLogProto logList = 1;
}
//公会成员权限管理,同意申请，踢人等。
message GuildMemberAuthRequest_40000041 {
  repeated uint32  targetPidList = 1;//操作的玩家id集合
  int32 optType = 2; //1 申请同意加入， 2 申请拒绝加入， 3 踢人
}
message GuildMemberAuthResponse_40000042{
  bool result = 1;
}

//通知目标加入公会
message GuildJoinPush_40000044 {
  repeated uint32 targetPids = 1;//被通知的对象
  GuildSimpleInfo guild = 2;//公会对象
}

//公会砍价
message GuildBargainRequest_40000060{
}
message GuildBargainResponse_40000061{
  int32 count = 1;//	砍掉了多少
  repeated RewardInfo rewards = 2; // 砍价给的奖励
}

//购买公会砍价物品
message GuildBargainBuyRequest_40000062{
}
message GuildBargainBuyResponse_40000063{
  repeated RewardInfo rewards = 1; //
}

//快速一键加入公会
message GuildQuickJoinRequest_40000065{
}
message GuildQuickJoinResponse_40000066{
  GuildAllInfo guild = 1;
}


//公会捐献
message GuildDonateRequest_40000067{
  int32 id = 1;  // 捐献id， GuildDonate 表id
}
message GuildDonateResponse_40000068{
  repeated RewardInfo rewards = 1; // 获得的奖励
}



//请求工会排行榜数据
message GuildRankListRequest_40000081{
  int32 page = 2; // 分页显示使用，当前页，从1开始，如果不分页设置1
  int32 pageSize = 3; // 每页显示数量。
}

message GuildRankListResponse_40000082{
  GuildRankList rankList = 1;
}

message GuildRankList{
  GuildRankInfo myRankInfo = 1; // 专门用来显示自己公会的排名数据
  repeated GuildRankInfo guildRanks = 3;  // 榜单数据
}

message GuildRankInfo{
  GuildSimpleInfo guild = 1;  //公会基本数据
  int32 rank = 2; //排名，-1或0表示没有进入排行榜，没有名次
  string score = 3; //参与排行的分数，这里是所有成员的战力总和
}

message GuildGVECardData{
    int32 cardId = 1;//  ID 
    int32 cardStaus = 2;// 状态 0 未   1已
	int64 playerId = 3;//  
	string playerName = 4;//
	int32 rewardId = 5;//   掉落包Id
}

// 联盟服与游戏服通信数据结构
message GuildGVECardDataResponse{
  repeated GuildGVECardData card1 = 1;  // 榜单数据  101-181   
  repeated GuildGVECardData card10 = 2;  // 榜单数据  201-281
  repeated GuildGVECardData card100 = 3;  // 榜单数据  301-381
}
// 联盟服与游戏服通信数据结构
message GuildGVEOpenCardResponseData{
  int32 result = 1; //
  GuildGVECardData cardData=2;
}
// 客户端与游戏服通信  请求数据
message GuildGVECardDataRequest_40000083{

}
// 客户端与游戏服通信  返回数据
message GuildGVECardDataResponse_40000084{
  repeated GuildGVECardData card1 = 1;  // 榜单数据  101-181   
  repeated GuildGVECardData card10 = 2;  // 榜单数据  201-281
  repeated GuildGVECardData card100 = 3;  // 榜单数据  301-381
  int32 myCount1 = 4;// 
  int32 myCount10 = 5;// 
  int32 myCount100 = 6;// 
}
// 客户端与游戏服通信  翻咔
message GuildGVEOpenCardRequest_40000085{
      int32 cardId =1;
}

// 客户端与游戏服通信  翻咔回包
message GuildGVEOpenCardResponse_40000086{
  repeated RewardInfo rewards = 1; //
  GuildGVECardData cardData=2;
  int32 result=3;
}
//︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻下面的客户端不用看了，用不到︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻


//︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻只服务器用到的协议︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻


//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼只服务器用到的协议︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼
//@NotUseStart
//︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻悬赏，目前没有这个功能，协议暂时保留︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻

//悬赏相关
message GuildBountyProto{
  GuildBountyMissionProto bountyMission = 1;
  int32 acceptCount = 3;  // 当天已经接取的悬赏次数。
  int32 refreshCount = 4; // 目标刷新次数
  int32 challengeCount = 5; // 挑战次数
}

//悬赏任务数据
message GuildBountyMissionProto{
  int32 id = 1;       //悬赏任务id： GuildBountyBar 表id
  int32 startPlace = 2;   //  悬赏任务的起点 GuildBargainPlace 表id
  int32 endPlace = 3;   //  悬赏任务的终点 GuildBargainPlace 表id
  int32 state = 4 ;     // "任务状态, 2:可接 3:已接（进行中，未完成）4: 任务结束,可领奖。
  int32 startTime = 5 ;   // 针对state是3 已接的任务，任务的接受时间(秒时间戳)
  int32 endTime = 6 ;     // 针对state是3 已接的任务，任务的实际结束时间(秒时间戳，算上了)
}
//参与悬赏任务的玩家
message GuildBountyPlayerProto{
  SimplePlayerInfo player = 1;//玩家信息
  GuildBountyMissionProto mission = 2; //悬赏任务数据
}
//公会悬赏任务战报
message GuildBountyBattleReport{
  string uid = 1;     // 战报唯一id
  int32 id = 2;       //悬赏任务id： GuildBountyBar 表id
  int32 attackTime = 3;   //挑战时间， 秒时间戳
  string attackerId = 4;  //挑战者id
  string attackerName = 5;  //挑战者名字
  string attackerHead = 6;  //挑战者头像
  string playerName = 8;  //接任务者名字
  bool isWin = 9;       //挑战结果
  bool isLoss = 10;     //挑战成功时， 是否损失了奖励
}
//公会悬赏任务战报,带有挑战者的状态
message GuildBountyBattleReportAttacker{
  GuildBountyBattleReport report = 1;
  bool isAttatckerMission = 2;      //挑战者是否正在进行悬赏任务
}



// 接悬赏任务
message GuildBountyAcceptRequest_40000070{
}
message GuildBountyAcceptResponse_40000071{
}

// 领取当前悬赏任务奖励
message GuildBountyRewardRequest_40000072{
}
message GuildBountyRewardResponse_40000073{
  int32 event = 1;          //悬赏结束时产生的奇遇事件， GuildAdventureEvent 表id
  repeated RewardInfo eventRewards = 2; // 奇遇事件奖励
  repeated RewardInfo bountyRewards = 3; // 悬赏奖励
  GuildBountyProto bounty = 4;      // 更新悬赏数据，会有新的悬赏任务
}


// 刷新悬赏的目标列表
message GuildBountyTargetRefreshRequest_40000074{
}
message GuildBountyTargetRefreshResponse_40000075{
  repeated GuildBountyPlayerProto players = 1;
}


// 悬赏挑战、 反击  开始战斗
message GuildBountyBattleStartRequest_40000076{
  string playerId = 1;  // 攻击的玩家id
}
message GuildBountyBattleStartResponse_40000077{
}

// 悬赏挑战、 反击  结束战斗
message GuildBountyBattleEndRequest_40000078{
  string playerId = 1;  // 攻击的玩家id
  bool isWin = 2;     // 是否胜利
}
message GuildBountyBattleEndResponse_40000079{
}
// 悬赏战报
message GuildBountyBattleReportRequest_4000007a{
  bool isGuild = 1;  // true ：查看公会战报， false：查看个人战报
}
message GuildBountyBattleReportResponse_4000007b{
  repeated  GuildBountyBattleReportAttacker reports = 1;
}
// 查看某个玩家当前的悬赏详情
message GuildBountyPlayerRequest_4000007c{
  string playerId = 1;
}
message GuildBountyPlayerResponse_4000007d{
   SimplePlayerInfo player = 1;//玩家基本数据
   GuildBountyMissionProto mission = 2; // 悬赏数据，如果没有进行中的悬赏任务，则为null
}

//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼悬赏，目前没有这个功能，协议暂时保留︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼

//@NotUseEnd
