syntax = "proto3";
package cn.game.protocol.protobuf;
//option optimize_for = LITE_RUNTIME;

import "BaseMsg.proto" ;
//@File 排行榜相关协议

//@HandlerPackage cn.game.games.net.game.module.rank
//@MessageModule 35

//请求排行榜数据
message RankListRequest_35000001{
  int32 type = 1; // RankType表id
  int32 page = 2; // 分页显示使用，当前页，从1开始，如果不分页设置1
  int32 pageSize = 3; // 每页显示数量。
}

message RankListResponse_35000002{
	RankInfo rankInfo = 1;
}

message RankInfo{
	PlayerRankInfo myRankInfo = 1; // 专门用来显示自己的排名数据
	repeated PlayerRankInfo players = 3;  // 榜单数据
}

