syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "RewardMsg.proto" ;
//import "BaseMsg.proto" ;

//@HandlerPackage cn.game.games.net.game.module.item
//@MessageModule 0b

// 道具相关协议
//使用道具
message ItemUseRequest_0b000003{
     uint32 id = 1;				//道具ID（Item表id）
     uint32 count = 2;		    //使用数量
     uint32 param = 3;          // 道具使用参数，比如当道具的ItemType为4任选道具时，为Item表 Para1参数索引
}

// 使用道具后可能会给资源，道具等。
message ItemUseResponse_0b000004{
	 repeated RewardInfo reward  = 1; // 获取的东西
}


// 出售道具
message ItemSellRequest_0b000007{
     repeated uint32 id = 1;			//道具ID（Item表id）
     repeated uint32 count = 2;		    //出售数量，id和数量顺序要对应
}

// 出售道具返回
message ItemSellResponse_0b000008{
	 repeated RewardInfo reward  = 1; // 出售后获取的东西
}
