syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "RewardMsg.proto" ;
import "BaseMsg.proto" ;

//宗门简单信息
message ZongMenSimpleInfoProto{
  uint32 id = 1; //宗门id
  string name = 2; //宗门名称
  int32 level = 3; //宗门等级
  int32 icon = 4; //宗门ICON
  int32 memberNum = 5; //成员数量
  int32 totalPower = 6; //总战力
  int32  isAutoJoin = 7; //1 快速加入、2 需要验证加入、3 不可加入；
  int32 tianDaoLevel = 8; //天道的等级
  repeated uint32 applyPidList = 9;//当前的申请加入列表
}
//宗门成员信息
message ZongMenMemberProto{
  uint32 pid = 1;//玩家id
  SimplePlayerInfo simplePlayer = 2;//玩家信息
  int32 todayContribute = 3;//今日贡献
  int32 totalContribute = 4;//累计历史贡献
  int32 joinTime = 5;//加入时间
  int32 position = 6;//职位

}
//宗门设置相关
message ZongMenSettingProto{
  string wx = 1;//宗主的微信号
  int32 wxChangeNum = 2;//微信号修改次数
  string notice = 3;//公告
  string declaration = 4;//宣言
  map<int32,int32> iconList = 5;//解锁的ICON列表 key ICON id, value 剩余时间戳 秒， -1 表示永久
  int32 lastChangeNameTimer = 6;//最后修改名称时间
  int32 lastChangeWxTimer = 7;//最后修改微信号时间
}
//宗门砍价相关
message ZongMenBargainProto{
  int32 bargainItemId = 1;//刷新出来的砍价物品id ： GuildBargain 表id
  int32 totalMemberCount = 2;//累计砍价的人数
  int32 totalBargainCount = 3;//累计砍掉的价格

  bool isBargain = 5;//是否砍过价
  bool isBargainBuy = 6;//是否购买了砍价的物品
  //宗门砍价记录 key: 砍价人的名字 value: 砍掉的数量
  map<string,int32> bargainLogMap = 7;
}

//宗门操作日志
message ZongMenLogProto{
  int32  createTimer = 1;//创建时间
  int32  type = 3;//操作类型
  repeated string params = 4;//参数 更具操作类型不同
}
//宗门商店
message ZongMenShopProto{
  int64 nextRefreshTimer = 1;//商店下一次刷新时间戳
  map<int32,int32> itemBuyNumMap = 2;//商店物品购买次数 key 物品id，val 购买数量
}
//宗门悬赏
message ZongMenXuanShangProto{

}
//宗门任务相关
message ZongMenTaskProto{
  int32 liveness = 1;//活跃度
  repeated int32  rewardIdList = 2;//领取的活跃度奖励集合
}
//宗门活动
message ZongMenActivityProto{

}

//宗门相关
message ZongMenInfoProto{
  ZongMenSimpleInfoProto simpleInfo = 1; //简单信息
  int32 exp = 2; //宗门经验
  ZongMenSettingProto setting = 3; //设置信息
  repeated ZongMenMemberProto memberList = 4; //成员列表
  repeated SimplePlayerInfo applyList = 5;//申请列表
  repeated ZongMenLogProto logList = 6;//操作日志 废弃 不下发
  ZongMenShopProto shop = 7;//商店 废弃 不下发
  ZongMenXuanShangProto xuanShang = 8;//悬赏
  int32 liveness = 9;//活跃度
  ZongMenBargainProto bargain = 15;//砍价相关，一般只有查看自己所在宗门，这个数据才有效
}

//宗门列表
message  getZongMenListRequest_40000001{
  int32 page = 1;//页码 从1开始 默认1页20条数据
}
message  getZongMenListResponse_40000002{
  repeated ZongMenSimpleInfoProto zongMenList = 1;
  int32 total = 2;//总条数
  int32 page = 3;//当前页码
}

//查找宗门
message  findZongMenRequest_40000003{
  uint32 id = 1;//宗门id
}
message  findZongMenResponse_40000004{
  ZongMenInfoProto zongMen = 1;
}

//创建宗门
message  createZongMenRequest_40000005{
  string name = 1;//宗门名称
  string notice = 2;//公告
  string declaration = 3;//宣言
  int32 icon = 4;//ICON
}
message  createZongMenResponse_40000006{
  ZongMenInfoProto zongMen = 1;
}

//申请加入宗门
message  applyJoinZongMenRequest_40000007{
  uint32 id = 1;//宗门id
}
message  applyJoinZongMenResponse_40000008{
  ZongMenInfoProto zongMen = 1;
}



//解散宗门
message  dissolveZongMenRequest_40000011{
}
message  dissolveZongMenResponse_40000012{
  bool result = 1;//是否成功
}

//宗门设置相关 有值 则替换，没有值 则不修改
message  setZongMenSettingRequest_40000013{
  string wx = 1;//微信号
  string notice = 2;//公告
  string declaration = 3;//宣言
  int32 icon = 4;//ICON
  int32 autoJoin = 5;//1 快速加入、2 需要验证加入、3 不可加入；
  int32 tianDaoLevel = 6;//天道的等级
  string name = 7;//宗门名称
}
message  setZongMenSettingResponse_40000014{
  bool result = 1;//是否成功
}

//宗门权限管理
message  setZongMenMemberPositionRequest_40000015{
  uint32 targetPid = 1;//目标玩家id
  int32 position = 2;//新的职位
}
message  setZongMenMemberPositionResponse_40000016{
  bool result = 1;//是否成功
  int32 position = 2;//新的职位
  uint32 targetPid = 3;//目标玩家id
}
//退出宗门
message  quitZongMenRequest_40000017{
}
message  quitZongMenResponse_40000018{
  bool result = 1;//是否成功
}

//获取宗门信息
message  getZongMenInfoRequest_40000021{
}
message getZongMenInfoResponse_40000022{
  ZongMenInfoProto info = 1;
}

//解散宗门 通知玩家退出宗门
message notifyQuitZongMen_40000024
{
}


//宗门日志请求
message getZongMenLogRequest_40000025{

}
message getZongMenLogResponse_40000026{
    repeated ZongMenLogProto logList = 1;
}

//宗门商店请求
message getZongMenShopRequest_40000027{
}
message getZongMenShopResponse_40000028{
     ZongMenShopProto shopList = 1;
}



//宗门任务请求
message getZongMenTaskRequest_40000031{
}
message getZongMenTaskResponse_40000032{
     ZongMenTaskProto taskList = 1;
}

//宗门活动请求
message getZongMenActivityRequest_40000033{
}
message getZongMenActivityResponse_40000034{

}
//宗门悬赏请求
message getZongMenXuanShangRequest_40000035{
}
message getZongMenXuanShangResponse_40000036{
  repeated ZongMenXuanShangProto xuanShangList = 1;
}

//更新宗门资产 宗门活跃度 宗门经验 个人贡献 ...
message updateZongMenAssetRequest_40000037 {
  repeated RewardInfo zongMenAssetMaps = 1;
}
message updateZongMenAssetResponse_40000038{

}

//宗门成员权限管理
message updateMemberAuthRequest_40000041 {
  repeated uint32  targetPidList = 1;//操作的玩家id集合
  int32 optType = 2; //1 申请同意加入， 2 申请拒绝加入， 3 踢人
}
message updateMemberAuthResponse_40000042{
  bool result = 1;
}

//通知目标加入宗门
message notifyJoinZongMen_40000044 {
  repeated uint32 targetPids = 1;//被通知的对象
  ZongMenInfoProto zongMen = 2;//宗门对象
}

//领取宗门活跃度奖励
message ZongMenActiveRewardRequest_40000045{
  repeated int32 indexList = 1;//要领取的活跃度 下标集合
}
message ZongMenActiveRewardResponse_40000046{
  repeated int32 rewardIndexList = 1;//当前领取的集合
  repeated RewardInfo drops = 2;//掉落
}

//购买宗门商店物品
message ZongMenBuyShopRequest_40000047{
  int32 itemId = 1;//商品id
  int32 count = 2;//购买数量
}
message ZongMenBuyShopResponse_40000048{
  repeated RewardInfo drops = 1;//掉落
}

//宗门砍价
message ZongMenBargainRequest_40000060{
}
message ZongMenBargainResponse_40000061{
  int32 count = 1;//	砍掉了多少
}


//购买宗门砍价物品
message ZongMenBargainBuyRequest_40000062{
}
message ZongMenBargainBuyResponse_40000063{
  repeated RewardInfo rewards = 1; //
}

//更新玩家战斗力
message ZongMenUpdateMemberFightPowerRequest_40000051{
  int64 pid = 1;//玩家id
  int32 fightPower = 2;//战斗力
}
message ZongMenUpdateMemberFightPower_40000052{
  bool result = 1;
}

//宗门 GM 操作
message ZongMenGmTestRequest_40000053{
  string cmd = 1;//命令
  repeated string param = 2;//参数
}
message ZongMenGmTestResponse_40000054{
  bool result = 1;//是否成功
}

//获取我已经申请的宗门id列表
message ZongMenGetMyApplyZongMenIdListRequest_40000055{
}
message ZongMenGetMyApplyZongMenIdListResponse_40000056{
  repeated uint32 zongMenIdList = 1;//宗门id集合
}

//更新宗门贡献值
message ZongMenUpdateContributeValueReq_40000057{
  bool isAdd = 1;//是否增加
  int32 value = 2;//增加的值
}
message ZongMenUpdateContributeValueRes_40000058{
  bool result = 1;
}
